### ISSUE TITLE
Compatibilité avec Jeedom 4.4 and Debian 12 Bookworm x64

### ISSUE THREAD

**Issue by paifre** [lucguinchard/plugin-Unifi#1]
Bonjour,

J'effectue actuellement une évaluation de la compatibilité de mes plugins avec Jeedom 4.4 sur **bookworm** dans une VM de test avec **PHP8**
J'ai le message d'erreur à l'activation du plugin:

`[2024-01-18 14:45:31][ERROR] : Erreur sur la fonction deamon_stop du plugin : socket_connect(): Argument #3 ($port) must be of type ?int, string given`

Je suis dispo pour d'éventuels tests sur une branche dédiée.
Merci par avance

**Comment by paifre** [comment]
Bonjour,

Je complète avec une information liée à la compatibilité PHP8 (string/array  @)

https://community.jeedom.com/t/aide-rpi-5-debian-12-zwavejs-razberry/115761

Merci

**Comment by lucguinchard** [comment]
Bonjour,

Merci de votre issue, je vais regarder effectivement. Pourquoi l'avez vous fermé ?

Bonne journée.
